apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow-workspaces

resources:
- ../../base
- rbac/tls

components:
- ../../components/prometheus
- ../../components/common
