apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redhat-ods-applications

resources:
- ../../base

components:
- ../../components/gateway
- ../../components/common

configMapGenerator:
- envs:
  - params.env
  name: kubeflow-workspaces-gateway-config

replacements:
- source:
    fieldPath: data.WORKBENCH_CONTROLLER_IMAGE
    kind: ConfigMap
    name: kubeflow-workspaces-gateway-config
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=manager].image
    select:
      kind: Deployment
      name: workspaces-controller

patches:
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: redhat-ods-applications
  target:
    kind: ClusterRoleBinding
    name: workspaces-manager-rolebinding
- patch: |-
    - op: replace
      path: /subjects/0/namespace
      value: redhat-ods-applications
  target:
    kind: RoleBinding
    name: workspaces-leader-election-rolebinding
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENABLE_WEBHOOKS
        value: "false"
    - op: remove
      path: /spec/template/spec/containers/0/securityContext/runAsUser
  target:
    kind: Deployment
    name: workspaces-controller
- patch: |-
    $patch: delete
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: validating-webhook-configuration
  target:
    kind: ValidatingWebhookConfiguration
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: webhook-service
  target:
    kind: Service
    name: webhook-service
